name: Lint and Format Check on Push

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        run: |
          cd packages/frontend
          npm install

      - name: Run ESLint and Prettier
        run: |
          cd packages/frontend
          npm run lint
          npx prettier --check "src/**/*.{js,jsx,ts,tsx}"

      - name: Check commit messages
        run: npx commitlint --from=HEAD~1 --to=HEAD
